site_name: ethopy
site_description: Python Boilerplate contains all the boilerplate you need to create a Python package.
site_author: alexevag
site_url: https://alexevag.github.io/ethopy
repo_url: https://github.com/alexevag/ethopy

copyright: "Copyright &copy; 2024 - 2024 Alex Evangelou"

theme:
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    logo: assets/LabPageBrain.gif
    favicon: assets/LabPageBrain.gif
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular
plugins:
    - search
    - mkdocstrings:
        handlers:
          python:
            paths: [src]
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore: ["*ignore.ipynb"]
          
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Task: task.md
    - Local congiguration: local_conf.md
    - Plugin System: plugin.md
    - Schemas: database.md
    - Gui: gui.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/alexevag/ethopy/issues
    - Examples:
        - examples/intro.ipynb
    - API Reference:
          - ethopy module: ethopy.md
          - Logger module: logger.md
          - Behavior module: behavior.md
          - Experiment module: experiment.md
          - Interface module: interface.md
          - Stimulus module: stimulus.md
